#version
version: "1.0"



# 站点设置
title: "onceOk Blog's"
email: 981446402@qq.com
description: "onceOk Blog's"
keywords: "Kyle"

# 用户信息设置
github_username: onceOk

# Markdown设置
kramdown:
  input:  GFM
  use_coderay: true
  coderay:
    coderay_line_numbers:  nil



# 地址设置
baseurl: "/onceOk.github.com"
url: "https://z981446402.github.io"


# 分页设置
paginate: 10
paginate_path: "page/:num"

#scss设置
sass:
    sass_dir: /assets/stylesheet
    style: :compressed

# duoshuo设置
duoshuo_shortname: z981446402

