#version
version: "1.0"



# 站点设置
title: "Kyle Blog's"
email: 981446402@qq.com
description: "Kyle 的个人博客"
keywords: "Kyle"

# 用户信息设置
weibo_username: Kyle
github_username: Kyle

# Markdown设置
kramdown:
  input:  GFM
  use_coderay: true
  coderay:
    coderay_line_numbers:  nil



# 地址设置
baseurl: "/kyle.github.com"
url: "https://z981446402.github.io"


# 分页设置
paginate: 10
paginate_path: "page/:num"

#scss设置
sass:
    sass_dir: /assets/stylesheet
    style: :compressed

# duoshuo设置
duoshuo_shortname: z981446402

# 百度统计设置
# baidu_analysis:
